#include "Compiler.h"
#include <ranges>
#include <stdexcept>
#include <algorithm>

Chunk Compiler::compile(ProgramNode* program) {
    compileProgram(program);
    chunk.emit(encodeABC(OpCode::OP_HALT, 0, 0, 0));
    
    // OPTIMIZATION: Run peephole optimizer on generated bytecode
    peepholeOptimize(chunk);
    
    return std::move(chunk);
}

void Compiler::compileNode(ASTNode* node) {
    switch (node->getType()) {
        case StmtType::Program: compileProgram(static_cast<ProgramNode*>(node)); return;
        case StmtType::Repeat: compileRepeat(static_cast<RepeatNode*>(node)); return;
        case StmtType::While: compileWhile(static_cast<WhileNode*>(node)); return;
        case StmtType::For: compileFor(static_cast<ForNode*>(node)); return;
        case StmtType::If: compileIf(static_cast<IfNode*>(node)); return;
        case StmtType::Print: compileLog(static_cast<PrintNode*>(node)); return;
        case StmtType::VarDecl: compileVarDecl(static_cast<VarDeclNode*>(node)); return;
        case StmtType::Assignment: compileAssignment(static_cast<AssignmentNode*>(node)); return;
        case StmtType::Wait: compileWait(static_cast<WaitNode*>(node)); return;
        case StmtType::Break: compileBreak(); return;
        case StmtType::Continue: compileContinue(); return;
        case StmtType::FunctionDecl: compileFunctionDecl(static_cast<FunctionDeclNode*>(node)); return;
        case StmtType::Return: compileReturn(static_cast<ReturnNode*>(node)); return;
        case StmtType::ClassDecl: compileClassDecl(static_cast<ClassDeclNode*>(node)); return;
        case StmtType::FieldAssign: compileFieldAssign(static_cast<FieldAssignNode*>(node)); return;
        case StmtType::ExprStmt: compileExprStmt(static_cast<ExpressionStmtNode*>(node)); return;
        case StmtType::IndexAssign: compileIndexAssign(static_cast<IndexAssignNode*>(node)); return;
        case StmtType::TryCatch: compileTryCatch(static_cast<TryCatchNode*>(node)); return;
        case StmtType::Throw: compileThrow(static_cast<ThrowNode*>(node)); return;
        default:
            throw std::runtime_error("Compiler: unknown AST node type");
    }
}

uint8_t Compiler::compileExpression(ExpressionNode* expr, uint8_t dst) {
    if (dst == 255) dst = allocReg();
    switch (expr->getType()) {
        case ExprType::Number: return compileNumber(static_cast<NumberNode*>(expr), dst);
        case ExprType::Double: return compileDouble(static_cast<DoubleNode*>(expr), dst);
        case ExprType::Boolean: return compileBoolean(static_cast<BooleanNode*>(expr), dst);
        case ExprType::String: return compileString(static_cast<StringNode*>(expr), dst);
        case ExprType::Variable: return compileVariable(static_cast<VariableNode*>(expr), dst);
        case ExprType::BinaryOp: return compileBinaryOp(static_cast<BinaryOperationNode*>(expr), dst);
        case ExprType::UnaryOp: return compileUnaryOp(static_cast<UnaryOperationNode*>(expr), dst);
        case ExprType::FunctionCall: return compileFunctionCall(static_cast<FunctionCallNode*>(expr), dst);
        case ExprType::FieldAccess: return compileFieldAccess(static_cast<FieldAccessNode*>(expr), dst);
        case ExprType::MethodCall: return compileMethodCall(static_cast<MethodCallNode*>(expr), dst);
        case ExprType::IndexAccess: return compileIndexAccess(static_cast<IndexAccessNode*>(expr), dst);
        case ExprType::ArrayAlloc: return compileArrayAlloc(static_cast<ArrayAllocNode*>(expr), dst);
        case ExprType::ArrayLiteral: return compileArrayLiteral(static_cast<ArrayLiteralNode*>(expr), dst);
        case ExprType::StringInterp: return compileStringInterp(static_cast<StringInterpNode*>(expr), dst);
        default:
            throw std::runtime_error("Compiler: unknown expression node type");
    }
}

void Compiler::compileProgram(ProgramNode* node) {
    for (auto& stmt : node->statements) {
        compileNode(stmt.get());
    }
}

void Compiler::compileLog(PrintNode* node) {
    uint8_t save = nextReg;
    uint8_t r = compileExpression(node->msg.get());
    chunk.emit(encodeABC(OpCode::OP_LOG, r, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileWait(WaitNode* node) {
    uint8_t save = nextReg;
    uint8_t r = compileExpression(node->duration.get());
    chunk.emit(encodeABC(OpCode::OP_WAIT, r, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileVarDecl(VarDeclNode* node) {
    const TypeAnnotation annot = node->typeAnnotation;
    if (isGlobalScope()) {
        uint16_t slot;
        auto it = globalIndex.find(node->nameOfVariable);
        if (it == globalIndex.end()) {
            slot = globalCount++;
            globalIndex[node->nameOfVariable] = slot;
        } else {
            slot = it->second;
        }
        uint8_t save = nextReg;
        uint8_t r = compileExpression(node->expression.get());
        // Runtime type check if annotation is present
        if (annot != TypeAnnotation::None)
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, r, static_cast<uint8_t>(annot), 0));
        chunk.emit(encodeABC(OpCode::OP_DGLOB, r, static_cast<uint8_t>(slot >> 8), static_cast<uint8_t>(slot & 0xFF)));
        freeRegsTo(save);
    } else {
        addLocal(node->nameOfVariable, node->isMutable, annot);
        int idx = resolveLocal(node->nameOfVariable);
        compileExpression(node->expression.get(), locals[idx].reg);
        // Runtime type check if annotation is present
        if (annot != TypeAnnotation::None)
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(annot), 0));
    }

    // Track class type for field/method access
    if (node->expression->getType() == ExprType::FunctionCall) {
        auto* call = static_cast<FunctionCallNode*>(node->expression.get());
        if (classIndex.contains(call->name)) {
            varClassMap[node->nameOfVariable] = call->name;
        }
    }
}

void Compiler::compileAssignment(AssignmentNode* node) {
    int arg = resolveLocal(node->nameOfVariable);
    if (arg != -1) {
        if (!locals[arg].isMutable) throw std::runtime_error("Variable is immutable.");
        compileExpression(node->expression.get(), locals[arg].reg);
    } else {
        auto it = globalIndex.find(node->nameOfVariable);
        if (it == globalIndex.end()) throw std::runtime_error("Undefined variable.");
        uint8_t save = nextReg;
        uint8_t r = compileExpression(node->expression.get());
        chunk.emit(encodeABx(OpCode::OP_SGLOB, r, it->second));
        freeRegsTo(save);
    }
}

void Compiler::compileIf(IfNode* node) {
    uint8_t save = nextReg;
    uint8_t cond = compileExpression(node->condition.get());

    size_t thenJump = chunk.emitJump(OpCode::OP_JMPF, cond);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->thenBlock) compileNode(stmt.get());
    endScope();

    size_t elseJump = chunk.emitJump(OpCode::OP_JMP);
    chunk.patchJump(thenJump);

    beginScope();
    for (auto& stmt : node->elseBlock) compileNode(stmt.get());
    endScope();

    chunk.patchJump(elseJump);
}

void Compiler::compileWhile(WhileNode* node) {
    const size_t loopStart = chunk.code.size();
    loopStack.push_back({loopStart, {}, scopeDepth});

    uint8_t save = nextReg;
    uint8_t cond = compileExpression(node->condition.get());

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, cond);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
}

void Compiler::compileFor(const ForNode* node) {
    beginScope();
    if (node->init) compileNode(node->init.get());

    const size_t loopStart = chunk.code.size();
    uint8_t save = nextReg;
    uint8_t cond = compileExpression(node->condition.get());

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, cond);
    freeRegsTo(save);

    loopStack.push_back({0, {}, scopeDepth});

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    loopStack.back().loopStart = chunk.code.size();
    if (node->increment) compileNode(node->increment.get());

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
    endScope();
}

void Compiler::compileRepeat(RepeatNode* node) {
    beginScope();
    const std::string counterName = "$__repeat_" + std::to_string(repeatCounter++);
    addLocal(counterName, true);

    int counterIdx = resolveLocal(counterName);
    uint8_t counterReg = locals[counterIdx].reg;

    compileExpression(node->count.get(), counterReg);

    const size_t loopStart = chunk.code.size();
    loopStack.push_back({loopStart, {}, scopeDepth});

    uint8_t save = nextReg;
    uint8_t zeroReg = allocReg();
    chunk.emit(encodeABx(OpCode::OP_LOADINT, zeroReg, static_cast<uint16_t>(0 + 32767)));
    uint8_t condReg = allocReg();
    chunk.emit(encodeABC(OpCode::OP_GT, condReg, counterReg, zeroReg));

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, condReg);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    save = nextReg;
    uint8_t oneReg = allocReg();
    chunk.emit(encodeABx(OpCode::OP_LOADINT, oneReg, 1 + 32767));
    chunk.emit(encodeABC(OpCode::OP_SUB, counterReg, counterReg, oneReg));
    freeRegsTo(save);

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
    endScope();
}

void Compiler::compileBreak() {
    if (loopStack.empty()) throw std::runtime_error("'break' outside loop");
    loopStack.back().breakJumps.push_back(chunk.emitJump(OpCode::OP_JMP));
}

void Compiler::compileContinue() {
    if (loopStack.empty()) throw std::runtime_error("'continue' outside loop");
    chunk.emitLoop(loopStack.back().loopStart);
}

void Compiler::compileFunctionDecl(FunctionDeclNode* node) {
    uint16_t funcIdx = static_cast<uint16_t>(functions.size());
    functionIndex[node->name] = funcIdx;
    functions.push_back({});

    // Save compiler state
    Chunk savedChunk = std::move(chunk);
    std::vector<Local> savedLocals = std::move(locals);
    int savedScopeDepth = scopeDepth;
    auto savedLoopStack = std::move(loopStack);
    uint8_t savedNextReg = nextReg;
    uint8_t savedMaxReg = maxReg;

    // Reset for new function
    chunk = Chunk{};
    locals.clear();
    scopeDepth = 0;
    loopStack.clear();
    nextReg = 0;
    maxReg = 0;

    beginScope();
    // Add params as locals, emit OP_TYPECHECK for typed params
    for (auto& [pname, ptype] : node->params) {
        addLocal(pname, true, ptype);
        if (ptype != TypeAnnotation::None) {
            int idx = resolveLocal(pname);
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(ptype), 0));
        }
    }
    for (auto& stmt : node->body) compileNode(stmt.get());

    // Implicit return null
    uint8_t nullReg = allocReg();
    chunk.emit(encodeABC(OpCode::OP_LOADNULL, nullReg, 0, 0));
    chunk.emit(encodeABC(OpCode::OP_RET, nullReg, 0, 0));

    functions[funcIdx].name = node->name;
    functions[funcIdx].arity = static_cast<int>(node->params.size());
    functions[funcIdx].chunk = std::move(chunk);
    functions[funcIdx].maxRegs = maxReg;
    functions[funcIdx].returnType = node->returnType;
    // Store param types for call-site checking
    functions[funcIdx].paramTypes.reserve(node->params.size());
    for (auto& [pname, ptype] : node->params)
        functions[funcIdx].paramTypes.push_back(ptype);

    // Restore state
    chunk = std::move(savedChunk);
    locals = std::move(savedLocals);
    scopeDepth = savedScopeDepth;
    loopStack = std::move(savedLoopStack);
    nextReg = savedNextReg;
    maxReg = savedMaxReg;
}

void Compiler::compileReturn(ReturnNode* node) {
    // OPTIMIZATION: Enhanced Tail Call Detection
    // Detect more patterns for TCO including nested calls
    
    if (node->expression) {
        // Check for tail function call
        if (node->expression->getType() == ExprType::FunctionCall) {
            auto* call = static_cast<FunctionCallNode*>(node->expression.get());
            if (call->name != "print" && call->name != "wait" && 
                call->name != "array" && call->name != "len" && call->name != "super") {
                auto it = functionIndex.find(call->name);
                if (it != functionIndex.end()) {
                    uint8_t save = nextReg;
                    uint8_t base = nextReg;
                    for (auto& arg : call->args) {
                        uint8_t r = allocReg();
                        compileExpression(arg.get(), r);
                    }
                    chunk.emit(encodeABC(OpCode::OP_TAILCALL, base, 
                                        static_cast<uint8_t>(it->second & 0xFF), 
                                        static_cast<uint8_t>(call->args.size())));
                    freeRegsTo(save);
                    return;
                }
            }
        } 
        // Check for tail method call
        else if (node->expression->getType() == ExprType::MethodCall) {
            auto* call = static_cast<MethodCallNode*>(node->expression.get());
            if (call->objectName != "super") {
                uint8_t save = nextReg;
                uint8_t base = nextReg;
                const uint8_t objReg = allocReg();

                if (call->objectName == "this") {
                    int thisLocal = resolveLocal("this");
                    if (thisLocal == -1) 
                        throw std::runtime_error("this.method() must be called from a method");
                    if (locals[thisLocal].reg != objReg) 
                        chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
                } else {
                    int localIdx = resolveLocal(call->objectName);
                    if (localIdx != -1) {
                        if (locals[localIdx].reg != objReg) 
                            chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[localIdx].reg, 0));
                    } else {
                        auto gIt = globalIndex.find(call->objectName);
                        if (gIt == globalIndex.end()) 
                            throw std::runtime_error("Undefined variable '" + call->objectName + "'");
                        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
                    }
                }

                for (auto& arg : call->args) {
                    uint8_t r = allocReg();
                    compileExpression(arg.get(), r);
                }

                uint8_t totalArgs = static_cast<uint8_t>(call->args.size() + 1);
                uint16_t nameId = chunk.addConstant(Value(call->methodName));
                if (nameId > 255) 
                    throw std::runtime_error("Too many unique strings in chunk for OP_TAIL_INVOKE B byte");
                chunk.emit(encodeABC(OpCode::OP_TAIL_INVOKE, base, 
                                    static_cast<uint8_t>(nameId), totalArgs));
                freeRegsTo(save);
                return;
            }
        }
    }

    // Default return (not a tail call)
    const uint8_t save = nextReg;
    uint8_t r;
    if (node->expression) {
        r = compileExpression(node->expression.get());
    } else {
        r = allocReg();
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, r, 0, 0));
    }
    chunk.emit(encodeABC(OpCode::OP_RET, r, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileClassDecl(ClassDeclNode* node) {
    uint16_t clsId = static_cast<uint16_t>(classes.size());
    classIndex[node->name] = clsId;
    ClassMeta meta;
    meta.name = node->name;

    // === Inheritance: copy parent fields & methods ===
    if (!node->parentName.empty()) {
        auto parentIt = classIndex.find(node->parentName);
        if (parentIt == classIndex.end())
            throw std::runtime_error("Unknown parent class: " + node->parentName);
        
        uint16_t parentId = parentIt->second;
        meta.parentClassId = static_cast<int16_t>(parentId);
        auto& parentMeta = classes[parentId];

        // Copy parent fields (they come first in the layout)
        for (uint16_t i = 0; i < parentMeta.fields.size(); i++) {
            meta.fields.push_back(parentMeta.fields[i]);
            meta.fieldIndex[parentMeta.fields[i].name] = i;
        }

        // Copy parent methods (can be overridden later)
        for (auto& [methodName, funcIdx] : parentMeta.methodIndex) {
            meta.methodIndex[methodName] = funcIdx;
            meta.methodPublic[methodName] = parentMeta.methodPublic[methodName];
        }
        
        // Copy abstract methods requirement
        for (const auto& absM : parentMeta.abstractMethods) {
            meta.abstractMethods.push_back(absM);
        }
    }

    meta.isAbstract = node->isAbstract;

    // Add own fields (after parent fields)
    for (uint16_t i = 0; i < node->fields.size(); i++) {
        auto& f = node->fields[i];
        uint16_t fieldIdx = static_cast<uint16_t>(meta.fields.size());
        meta.fields.push_back({f.name, f.isMutable, f.isPublic});
        meta.fieldIndex[f.name] = fieldIdx;
    }

    // Compile methods as functions with implicit 'this' as first param
    std::string savedClassName = currentClassName;
    currentClassName = node->name;

    for (auto& m : node->methods) {
        auto* funcDecl = m.function.get();
        const std::string& methName = funcDecl->name;

        if (m.isAbstract) {
            if (!meta.isAbstract) {
                throw std::runtime_error("Class '" + meta.name + "' is not abstract and cannot contain abstract method '" + methName + "'");
            }
            // Add to abstract methods if not already there
            if (std::find(meta.abstractMethods.begin(), meta.abstractMethods.end(), methName) == meta.abstractMethods.end()) {
                meta.abstractMethods.push_back(methName);
            }
            meta.methodIndex[methName] = 0xFFFF; // Marker for abstract method
            meta.methodPublic[methName] = m.isPublic;
            continue; // Do NOT compile a body for abstract methods
        }

        // It is a concrete method. Remove from abstract methods list if it exists.
        auto it = std::find(meta.abstractMethods.begin(), meta.abstractMethods.end(), methName);
        if (it != meta.abstractMethods.end()) {
            meta.abstractMethods.erase(it);
        }

        // Insert 'this' as first parameter
        std::vector<std::pair<std::string, TypeAnnotation>> params;
        params.emplace_back("this", TypeAnnotation::None);
        for (auto& p : funcDecl->params) {
            params.push_back(p);
        }

        uint16_t funcIdx = static_cast<uint16_t>(functions.size());
        std::string qualName = node->name + "." + methName;
        functionIndex[qualName] = funcIdx;
        meta.methodIndex[methName] = funcIdx;
        meta.methodPublic[methName] = m.isPublic;
        functions.push_back({});

        // Save compiler state
        Chunk savedChunk = std::move(chunk);
        std::vector<Local> savedLocals = std::move(locals);
        int savedScopeDepth = scopeDepth;
        auto savedLoopStack = std::move(loopStack);
        uint8_t savedNextReg = nextReg;
        uint8_t savedMaxReg = maxReg;

        chunk = Chunk{};
        locals.clear();
        scopeDepth = 0;
        loopStack.clear();
        nextReg = 0;
        maxReg = 0;

        beginScope();
        for (auto& [pname, ptype] : params) {
            addLocal(pname, true, ptype);
            if (ptype != TypeAnnotation::None) {
                int idx = resolveLocal(pname);
                chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(ptype), 0));
            }
        }
        for (auto& stmt : funcDecl->body) compileNode(stmt.get());

        uint8_t nullReg = allocReg();
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, nullReg, 0, 0));
        chunk.emit(encodeABC(OpCode::OP_RET, nullReg, 0, 0));

        functions[funcIdx].name = qualName;
        functions[funcIdx].arity = static_cast<int>(params.size());
        functions[funcIdx].chunk = std::move(chunk);
        functions[funcIdx].maxRegs = maxReg;
        functions[funcIdx].returnType = funcDecl->returnType;
        functions[funcIdx].paramTypes.reserve(params.size());
        for (auto& [pn, pt] : params)
            functions[funcIdx].paramTypes.push_back(pt);

        chunk = std::move(savedChunk);
        locals = std::move(savedLocals);
        scopeDepth = savedScopeDepth;
        loopStack = std::move(savedLoopStack);
        nextReg = savedNextReg;
        maxReg = savedMaxReg;
    }

    if (!meta.isAbstract && !meta.abstractMethods.empty()) {
        throw std::runtime_error("Class '" + meta.name + "' is not abstract and does not implement abstract method '" + meta.abstractMethods[0] + "' from parent");
    }

    classes.push_back(std::move(meta));
    currentClassName = savedClassName;
}

void Compiler::compileFieldAssign(FieldAssignNode* node) {
    std::string className;
    if (node->objectName == "this") {
        className = currentClassName;
    } else {
        auto it = varClassMap.find(node->objectName);
        if (it == varClassMap.end()) throw std::runtime_error("Unknown class for '" + node->objectName + "'");
        className = it->second;
    }

    auto& meta = classes[classIndex[className]];
    auto fieldIt = meta.fieldIndex.find(node->fieldName);
    if (fieldIt == meta.fieldIndex.end())
        throw std::runtime_error("Unknown field '" + node->fieldName + "' on class '" + className + "'");

    // Access control: private fields only from inside the class
    if (!meta.fields[fieldIt->second].isPublic && currentClassName != className)
        throw std::runtime_error("Cannot access private field '" + node->fieldName + "'");
    if (!meta.fields[fieldIt->second].isMutable && node->objectName != "this")
        throw std::runtime_error("Cannot assign to immutable field '" + node->fieldName + "'");

    uint8_t save = nextReg;

    // Resolve object register
    uint8_t objReg;
    int localIdx = resolveLocal(node->objectName);
    if (localIdx != -1) {
        objReg = locals[localIdx].reg;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        objReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
    }

    uint8_t valReg = compileExpression(node->expression.get());
    chunk.emit(encodeABC(OpCode::OP_SET_FIELD, valReg, objReg, static_cast<uint8_t>(fieldIt->second)));
    freeRegsTo(save);
}

void Compiler::compileExprStmt(ExpressionStmtNode* node) {
    uint8_t save = nextReg;
    compileExpression(node->expression.get());
    freeRegsTo(save);
}

uint8_t Compiler::compileFieldAccess(FieldAccessNode* node, uint8_t dst) {
    std::string className;
    if (node->objectName == "this") {
        className = currentClassName;
    } else {
        auto it = varClassMap.find(node->objectName);
        if (it == varClassMap.end()) throw std::runtime_error("Unknown class for '" + node->objectName + "'");
        className = it->second;
    }

    auto& meta = classes[classIndex[className]];
    auto fieldIt = meta.fieldIndex.find(node->fieldName);
    if (fieldIt == meta.fieldIndex.end())
        throw std::runtime_error("Unknown field '" + node->fieldName + "' on class '" + className + "'");

    if (!meta.fields[fieldIt->second].isPublic && currentClassName != className)
        throw std::runtime_error("Cannot access private field '" + node->fieldName + "'");

    uint8_t save = nextReg;
    uint8_t objReg;
    int localIdx = resolveLocal(node->objectName);
    if (localIdx != -1) {
        objReg = locals[localIdx].reg;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        objReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
    }

    chunk.emit(encodeABC(OpCode::OP_GET_FIELD, dst, objReg, static_cast<uint8_t>(fieldIt->second)));
    freeRegsTo(save);
    return dst;
}

uint8_t Compiler::compileMethodCall(MethodCallNode* node, uint8_t dst) {
    if (node->objectName == "super") {
        if (currentClassName.empty()) throw std::runtime_error("super.method() can only be used inside a class");
        auto clsIt = classIndex.find(currentClassName);
        if (clsIt == classIndex.end()) throw std::runtime_error("Internal error");
        auto& meta = classes[clsIt->second];
        if (meta.parentClassId < 0) throw std::runtime_error("super used in class '" + currentClassName + "' which has no parent");
        
        auto& pMeta = classes[meta.parentClassId];
        auto pIt = pMeta.methodIndex.find(node->methodName);
        if (pIt == pMeta.methodIndex.end()) throw std::runtime_error("Unknown method '" + node->methodName + "' on parent class");
        if (pIt->second == 0xFFFF) throw std::runtime_error("Cannot call abstract method '" + node->methodName + "' via super");
        
        uint16_t funcIdx = pIt->second;
        uint8_t base = nextReg;
        uint8_t objReg = allocReg();
        
        int thisLocal = resolveLocal("this");
        if (thisLocal == -1) throw std::runtime_error("super.method() must be called from a method with 'this'");
        if (locals[thisLocal].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
        
        for (auto& arg : node->args) {
            uint8_t r = allocReg();
            compileExpression(arg.get(), r);
        }
        
        uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
        chunk.emit(encodeABC(OpCode::OP_CALL, base, static_cast<uint8_t>(funcIdx & 0xFF), totalArgs));
        freeRegsTo(base + 1);
        if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
        return dst;
    }

    uint8_t base = nextReg;
    const uint8_t objReg = allocReg();

    if (node->objectName == "this") {
        int thisLocal = resolveLocal("this");
        if (thisLocal == -1) throw std::runtime_error("this.method() must be called from a method");
        if (locals[thisLocal].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
    } else {
        int localIdx = resolveLocal(node->objectName);
        if (localIdx != -1) {
            if (locals[localIdx].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[localIdx].reg, 0));
        } else {
            auto gIt = globalIndex.find(node->objectName);
            if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
            chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
        }
    }

    // Static check if possible
    auto it = varClassMap.find(node->objectName);
    if (it != varClassMap.end() || node->objectName == "this") {
        std::string className = (node->objectName == "this") ? currentClassName : it->second;
        auto& meta = classes[classIndex[className]];
        if (meta.methodIndex.find(node->methodName) == meta.methodIndex.end()) {
            throw std::runtime_error("Unknown method '" + node->methodName + "' on static class '" + className + "'");
        }
        if (!meta.methodPublic[node->methodName] && currentClassName != className) {
            throw std::runtime_error("Cannot call private method '" + node->methodName + "'");
        }
    }

    // Compile args
    for (auto& arg : node->args) {
        uint8_t r = allocReg();
        compileExpression(arg.get(), r);
    }

    uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
    uint16_t nameId = chunk.addConstant(Value(node->methodName));
    if (nameId > 255) throw std::runtime_error("Too many unique strings in chunk for OP_INVOKE B byte");
    chunk.emit(encodeABC(OpCode::OP_INVOKE, base, static_cast<uint8_t>(nameId), totalArgs));

    freeRegsTo(base + 1);
    if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
    return dst;
}

uint8_t Compiler::compileFunctionCall(FunctionCallNode* node, uint8_t dst) {
    if (node->name == "print") {
        if (node->args.size() != 1) throw std::runtime_error("print() expects 1 arg");
        uint8_t save = nextReg;
        uint8_t r = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_LOG, r, 0, 0));
        freeRegsTo(save);
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, dst, 0, 0));
        return dst;
    }
    if (node->name == "wait") {
        if (node->args.size() != 1) throw std::runtime_error("wait() expects 1 arg");
        uint8_t save = nextReg;
        uint8_t r = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_WAIT, r, 0, 0));
        freeRegsTo(save);
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, dst, 0, 0));
        return dst;
    }

    // --- Collection constructors: array(), len() ---
    if (node->name == "array") {
        if (node->args.size() != 1) throw std::runtime_error("array() expects 1 arg (size)");
        uint8_t save = nextReg;
        uint8_t sizeReg = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeReg, 0));
        freeRegsTo(save);
        return dst;
    }
    if (node->name == "len") {
        if (node->args.size() != 1) throw std::runtime_error("len() expects 1 arg");
        uint8_t save = nextReg;
        uint8_t collReg = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_COLL_LEN, dst, collReg, 0));
        freeRegsTo(save);
        return dst;
    }
    // --- super(args) — call parent constructor ---
    if (node->name == "super") {
        if (currentClassName.empty())
            throw std::runtime_error("super() can only be used inside a class method");
        auto clsIt = classIndex.find(currentClassName);
        if (clsIt == classIndex.end())
            throw std::runtime_error("Internal error: current class not found");
        auto& meta = classes[clsIt->second];
        if (meta.parentClassId < 0)
            throw std::runtime_error("super() used in class '" + currentClassName + "' which has no parent");
        
        auto& parentMeta = classes[meta.parentClassId];
        auto parentInitIt = parentMeta.methodIndex.find("init");
        if (parentInitIt == parentMeta.methodIndex.end())
            throw std::runtime_error("Parent class '" + parentMeta.name + "' has no init() method");
        
        uint16_t parentInitIdx = parentInitIt->second;
        
        // Layout: R[base]=this, R[base+1..]=args
        uint8_t base = nextReg;
        uint8_t thisReg = allocReg();
        int thisLocal = resolveLocal("this");
        if (thisLocal == -1) throw std::runtime_error("super() must be called from a method with 'this'");
        if (locals[thisLocal].reg != thisReg)
            chunk.emit(encodeABC(OpCode::OP_MOVE, thisReg, locals[thisLocal].reg, 0));
        
        for (auto& arg : node->args) {
            uint8_t r = allocReg();
            compileExpression(arg.get(), r);
        }

        const uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
        chunk.emit(encodeABC(OpCode::OP_CALL, base, static_cast<uint8_t>(parentInitIdx & 0xFF), totalArgs));
        freeRegsTo(base + 1);
        
        if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
        return dst;
    }

    auto it = functionIndex.find(node->name);
    if (it == functionIndex.end()) {
        // Check if it's a class instantiation
        auto classIt = classIndex.find(node->name);
        if (classIt != classIndex.end()) {
            uint16_t clsId = classIt->second;
            auto& meta = classes[clsId];
            if (meta.isAbstract) throw std::runtime_error("Cannot instantiate abstract class '" + meta.name + "'");

            // Create new instance
            chunk.emit(encodeABx(OpCode::OP_NEW_OBJ, dst, clsId));

            // Call init() if exists
            auto initIt = meta.methodIndex.find("init");
            if (initIt != meta.methodIndex.end()) {
                uint8_t callBase = allocReg();
                chunk.emit(encodeABC(OpCode::OP_MOVE, callBase, dst, 0));
                for (auto& arg : node->args) {
                    uint8_t r = allocReg();
                    compileExpression(arg.get(), r);
                }
                uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
                chunk.emit(encodeABC(OpCode::OP_CALL, callBase, static_cast<uint8_t>(initIt->second & 0xFF), totalArgs));
                freeRegsTo(callBase);
            }
            return dst;
        }
        throw std::runtime_error("Undefined function: " + node->name);
    }

    uint8_t base = nextReg;
    for (auto& arg : node->args) {
        uint8_t r = allocReg();
        compileExpression(arg.get(), r);
    }

    chunk.emit(encodeABC(OpCode::OP_CALL, base, static_cast<uint8_t>(it->second & 0xFF), static_cast<uint8_t>(node->args.size())));
    freeRegsTo(base + 1);

    if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
    return dst;
}

uint8_t Compiler::compileNumber(NumberNode* node, uint8_t dst) {
    int val = node->value;
    if (val >= -32767 && val <= 32767) {
        chunk.emit(encodeABx(OpCode::OP_LOADINT, dst, static_cast<uint16_t>(val + 32767)));
    } else {
        uint16_t ki = chunk.addConstant(Value(val));
        chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    }
    return dst;
}

uint8_t Compiler::compileDouble(DoubleNode* node, uint8_t dst) {
    uint16_t ki = chunk.addConstant(Value(node->value));
    chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    return dst;
}

uint8_t Compiler::compileBoolean(BooleanNode* node, uint8_t dst) {
    chunk.emit(encodeABC(OpCode::OP_LOADBOOL, dst, node->value ? 1 : 0, 0));
    return dst;
}

uint8_t Compiler::compileString(StringNode* node, uint8_t dst) {
    uint16_t ki = chunk.addConstant(Value(node->value));
    chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    return dst;
}

uint8_t Compiler::compileVariable(VariableNode* node, uint8_t dst) {
    int arg = resolveLocal(node->nameOfVariable);
    if (arg != -1) {
        uint8_t srcReg = locals[arg].reg;
        if (srcReg != dst) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, srcReg, 0));
        return dst;
    }
    auto it = globalIndex.find(node->nameOfVariable);
    if (it == globalIndex.end()) throw std::runtime_error("Undefined variable.");
    chunk.emit(encodeABx(OpCode::OP_GGLOB, dst, it->second));
    return dst;
}

uint8_t Compiler::compileUnaryOp(UnaryOperationNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    uint8_t r = compileExpression(node->operand.get());
    if (node->operation == "!") chunk.emit(encodeABC(OpCode::OP_NOT, dst, r, 0));
    else if (node->operation == "-") chunk.emit(encodeABC(OpCode::OP_NEG, dst, r, 0));
    else throw std::runtime_error("Unknown unary operator");
    freeRegsTo(save);
    return dst;
}

uint8_t Compiler::compileBinaryOp(BinaryOperationNode* node, uint8_t dst) {
    static const std::unordered_map<std::string, OpCode> opTable = {
        {"+", OpCode::OP_ADD}, {"-", OpCode::OP_SUB}, {"*", OpCode::OP_MUL},
        {"/", OpCode::OP_DIV}, {"%", OpCode::OP_MOD},
        {"==", OpCode::OP_EQ}, {"!=", OpCode::OP_NEQ},
        {"<", OpCode::OP_LT}, {">", OpCode::OP_GT},
        {"<=", OpCode::OP_LE}, {">=", OpCode::OP_GE},
        {"&&", OpCode::OP_AND}, {"||", OpCode::OP_OR},
        {"&", OpCode::OP_BIT_AND}, {"|", OpCode::OP_BIT_OR}, {"^", OpCode::OP_BIT_XOR},
        {"<<", OpCode::OP_SHL}, {">>", OpCode::OP_SHR},
    };

    // OPTIMIZATION: Enhanced Constant Folding
    // Try to fold integer constants
    if (node->leftNode->getType() == ExprType::Number && node->rightNode->getType() == ExprType::Number) {
        int a = static_cast<NumberNode*>(node->leftNode.get())->value;
        int b = static_cast<NumberNode*>(node->rightNode.get())->value;
        const auto& op = node->operation;
        int result;
        bool folded = true;
        OpCode specializedOp = OpCode::OP_COUNT;
        
        if (op == "+") { result = a + b; specializedOp = OpCode::OP_ADD_INT; }
        else if (op == "-") { result = a - b; specializedOp = OpCode::OP_SUB_INT; }
        else if (op == "*") { result = a * b; specializedOp = OpCode::OP_MUL_INT; }
        else if (op == "/" && b != 0) { result = a / b; specializedOp = OpCode::OP_DIV_INT; }
        else if (op == "%" && b != 0) { result = a % b; }
        else if (op == "==") { result = (a == b); folded = false; }  // boolean result
        else if (op == "!=") { result = (a != b); folded = false; }
        else if (op == "<") { result = (a < b); folded = false; }
        else if (op == ">") { result = (a > b); folded = false; }
        else if (op == "<=") { result = (a <= b); folded = false; }
        else if (op == ">=") { result = (a >= b); folded = false; }
        else if (op == "&") { result = a & b; }
        else if (op == "|") { result = a | b; }
        else if (op == "^") { result = a ^ b; }
        else if (op == "<<") { result = a << b; }
        else if (op == ">>") { result = a >> b; }
        else folded = false;
        
        if (folded) {
            if (result >= -32767 && result <= 32767) {
                chunk.emit(encodeABx(OpCode::OP_LOADINT, dst, static_cast<uint16_t>(result + 32767)));
            } else {
                uint16_t ki = chunk.addConstant(Value(result));
                chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
            }
            return dst;
        }
    }
    
    // Try to fold double constants
    if (node->leftNode->getType() == ExprType::Double && node->rightNode->getType() == ExprType::Double) {
        double a = static_cast<DoubleNode*>(node->leftNode.get())->value;
        double b = static_cast<DoubleNode*>(node->rightNode.get())->value;
        const auto& op = node->operation;
        double result;
        bool folded = true;
        
        if (op == "+") result = a + b;
        else if (op == "-") result = a - b;
        else if (op == "*") result = a * b;
        else if (op == "/" && b != 0.0) result = a / b;
        else if (op == "==") { result = (a == b) ? 1.0 : 0.0; }
        else if (op == "!=") { result = (a != b) ? 1.0 : 0.0; }
        else if (op == "<") { result = (a < b) ? 1.0 : 0.0; }
        else if (op == ">") { result = (a > b) ? 1.0 : 0.0; }
        else if (op == "<=") { result = (a <= b) ? 1.0 : 0.0; }
        else if (op == ">=") { result = (a >= b) ? 1.0 : 0.0; }
        else folded = false;
        
        if (folded) {
            // Check if result is actually an integer
            if (result == static_cast<double>(static_cast<int>(result))) {
                int intResult = static_cast<int>(result);
                if (intResult >= -32767 && intResult <= 32767) {
                    chunk.emit(encodeABx(OpCode::OP_LOADINT, dst, static_cast<uint16_t>(intResult + 32767)));
                } else {
                    uint16_t ki = chunk.addConstant(Value(intResult));
                    chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
                }
            } else {
                uint16_t ki = chunk.addConstant(Value(result));
                chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
            }
            return dst;
        }
    }

    uint8_t save = nextReg;
    uint8_t rB = compileExpression(node->leftNode.get());
    uint8_t rC = compileExpression(node->rightNode.get());

    auto it = opTable.find(node->operation);
    if (it == opTable.end()) throw std::runtime_error("Unknown binary operator");
    chunk.emit(encodeABC(it->second, dst, rB, rC));
    freeRegsTo(save);
    return dst;
}

void Compiler::beginScope() {
    scopeDepth++;
}

void Compiler::endScope() {
    scopeDepth--;
    while (!locals.empty() && locals.back().depth > scopeDepth) {
        locals.pop_back();
        freeReg();
    }
}

void Compiler::addLocal(const std::string& name, bool isMutable, TypeAnnotation typeAnnot) {
    for (auto & local : std::ranges::reverse_view(locals)) {
        if (local.depth < scopeDepth) break;
        if (local.name == name) throw std::runtime_error("Variable redeclared: " + name);
    }
    uint8_t r = allocReg();
    locals.push_back({name, scopeDepth, isMutable, r, typeAnnot});
}

int Compiler::resolveLocal(const std::string& name) {
    for (int i = locals.size() - 1; i >= 0; i--) {
        if (locals[i].name == name) return i;
    }
    return -1;
}

uint8_t Compiler::compileIndexAccess(IndexAccessNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    uint8_t collReg = compileExpression(node->object.get());
    uint8_t idxReg = compileExpression(node->index.get());
    chunk.emit(encodeABC(OpCode::OP_IDX_GET, dst, collReg, idxReg));
    freeRegsTo(save);
    return dst;
}

void Compiler::compileIndexAssign(IndexAssignNode* node) {
    uint8_t save = nextReg;

    // Resolve collection register
    uint8_t collReg;
    int localIdx = resolveLocal(node->objectName);
    if (localIdx != -1) {
        collReg = locals[localIdx].reg;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        collReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, collReg, gIt->second));
    }

    uint8_t idxReg = compileExpression(node->index.get());
    uint8_t valReg = compileExpression(node->value.get());
    chunk.emit(encodeABC(OpCode::OP_IDX_SET, valReg, collReg, idxReg));
    freeRegsTo(save);
}

uint8_t Compiler::compileArrayAlloc(ArrayAllocNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    uint8_t sizeReg = compileExpression(node->size.get());

    uint8_t elemType = 0; // UNTYPED
    if (node->elementType == TypeAnnotation::Int || node->elementType == TypeAnnotation::IntArray) elemType = 1; // INT
    else if (node->elementType == TypeAnnotation::Double || node->elementType == TypeAnnotation::DoubleArray) elemType = 2; // DOUBLE
    else if (node->elementType == TypeAnnotation::String || node->elementType == TypeAnnotation::StringArray) elemType = 3; // VALUE
    else if (node->elementType == TypeAnnotation::Bool || node->elementType == TypeAnnotation::BoolArray) elemType = 3; // VALUE

    chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeReg, elemType));
    freeRegsTo(save);
    return dst;
}

uint8_t Compiler::compileArrayLiteral(ArrayLiteralNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    int size = node->elements.size();

    uint8_t sizeReg = allocReg();
    if (size >= -32767 && size <= 32767) {
        chunk.emit(encodeABx(OpCode::OP_LOADINT, sizeReg, static_cast<uint16_t>(size + 32767)));
    } else {
        uint16_t ki = chunk.addConstant(Value(size));
        chunk.emit(encodeABx(OpCode::OP_LOADK, sizeReg, ki));
    }

    // Creating untyped array first, the elements will determine the final type through IDX_SET updates.
    chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeReg, 0));

    for (int i = 0; i < size; ++i) {
        uint8_t valSave = nextReg;
        uint8_t valReg = compileExpression(node->elements[i].get());

        uint8_t idxReg = allocReg();
        if (i >= -32767 && i <= 32767) {
            chunk.emit(encodeABx(OpCode::OP_LOADINT, idxReg, static_cast<uint16_t>(i + 32767)));
        } else {
            uint16_t ki = chunk.addConstant(Value(i));
            chunk.emit(encodeABx(OpCode::OP_LOADK, idxReg, ki));
        }

        chunk.emit(encodeABC(OpCode::OP_IDX_SET, valReg, dst, idxReg));
        freeRegsTo(valSave);
    }

    freeRegsTo(save);
    return dst;
}

void Compiler::compileTryCatch(TryCatchNode* node) {
    uint8_t catchVarReg = allocReg();  // allocate early so it's immune to try block regs
    
    // OP_PUSH_HANDLER catchVarReg, Bx = offset to catch block
    uint32_t pushInstrIndex = chunk.code.size();
    chunk.emit(encodeABx(OpCode::OP_PUSH_HANDLER, catchVarReg, 0)); // 0 is placeholder

    // Try block
    for (auto& stmt : node->tryBody) {
        compileNode(stmt.get());
    }

    // After success, POP_HANDLER and jump over catch
    chunk.emit(encodeABC(OpCode::OP_POP_HANDLER, 0, 0, 0));
    uint32_t jmpOverCatch = chunk.code.size();
    chunk.emit(encodesBx(OpCode::OP_JMP, 0)); // placeholder

    // Patch OP_PUSH_HANDLER
    uint32_t catchStart = chunk.code.size();
    int16_t catchOffset = static_cast<int16_t>(catchStart - (pushInstrIndex + 1));
    // Re-encode push instruction
    chunk.code[pushInstrIndex] = encodeABx(OpCode::OP_PUSH_HANDLER, catchVarReg, static_cast<uint16_t>(catchOffset));

    // Catch block
    beginScope();
    addLocal(node->catchVar, true, TypeAnnotation::None);
    locals.back().reg = catchVarReg; // use the register we picked
    
    // Catch body
    for (auto& stmt : node->catchBody) {
        compileNode(stmt.get());
    }
    endScope();

    nextReg = catchVarReg; // free the register

    // Patch jump over catch
    uint32_t endCatch = chunk.code.size();
    int16_t offsetToEnd = static_cast<int16_t>(endCatch - (jmpOverCatch + 1));
    chunk.code[jmpOverCatch] = encodesBx(OpCode::OP_JMP, offsetToEnd);
}

uint8_t Compiler::compileStringInterp(StringInterpNode* node, uint8_t dst) {
    if (node->parts.empty()) {
        chunk.emit(encodeABx(OpCode::OP_LOADK, dst, (uint16_t)chunk.addConstant(Value(""))));
        return dst;
    }

    uint8_t save = nextReg;
    uint8_t resReg = compileExpression(node->parts[0].get());
    if (resReg != dst) {
        chunk.emit(encodeABC(OpCode::OP_MOVE, dst, resReg, 0));
    }

    for (size_t i = 1; i < node->parts.size(); i++) {
        uint8_t r = compileExpression(node->parts[i].get());
        chunk.emit(encodeABC(OpCode::OP_ADD, dst, dst, r));
    }

    freeRegsTo(save); // free up all temporary registers inside interpolation
    return dst;
}

void Compiler::compileThrow(ThrowNode* node) {
    uint8_t save = nextReg;
    uint8_t r = compileExpression(node->expression.get());
    chunk.emit(encodeABC(OpCode::OP_THROW, r, 0, 0));
    freeRegsTo(save);
}

// OPTIMIZATION: Peephole Optimizer
// Applies local pattern-based optimizations to reduce instruction count and improve performance
void Compiler::peepholeOptimize(Chunk& ch) {
    auto& code = ch.code;
    if (code.empty()) return;
    
    bool changed = true;
    int iterations = 0;
    const int MAX_ITERATIONS = 10;  // Prevent infinite loops
    
    while (changed && iterations < MAX_ITERATIONS) {
        changed = false;
        iterations++;
        
        for (size_t i = 0; i + 1 < code.size(); i++) {
            uint32_t instr1 = code[i];
            uint32_t instr2 = code[i + 1];
            
            OpCode op1 = DECODE_OP(instr1);
            OpCode op2 = DECODE_OP(instr2);
            
            uint8_t A1 = DECODE_A(instr1);
            uint8_t B1 = DECODE_B(instr1);
            uint8_t C1 = DECODE_C(instr1);
            uint16_t Bx1 = DECODE_Bx(instr1);
            
            uint8_t A2 = DECODE_A(instr2);
            uint8_t B2 = DECODE_B(instr2);
            uint8_t C2 = DECODE_C(instr2);
            uint16_t Bx2 = DECODE_Bx(instr2);
            
            // Pattern 1: LOADINT R1, X → MOVE R2, R1 → LOADINT R2, X
            if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_MOVE) {
                code[i + 1] = encodeABx(OpCode::OP_LOADINT, A2, Bx1);
                changed = true;
                continue;
            }
            
            // Pattern 2: LOADINT R1, X → LOADINT R2, Y → ADD R3, R1, R2 → LOADINT R3, X+Y
            if (i + 2 < code.size()) {
                uint32_t instr3 = code[i + 2];
                OpCode op3 = DECODE_OP(instr3);
                uint8_t A3 = DECODE_A(instr3);
                uint8_t B3 = DECODE_B(instr3);
                uint8_t C3 = DECODE_C(instr3);
                
                if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_LOADINT && 
                    op3 == OpCode::OP_ADD && B3 == A1 && C3 == A2) {
                    int val1 = static_cast<int>(Bx1) - 32767;
                    int val2 = static_cast<int>(Bx2) - 32767;
                    int result = val1 + val2;
                    if (result >= -32767 && result <= 32767) {
                        code[i] = encodeABx(OpCode::OP_LOADINT, A3, static_cast<uint16_t>(result + 32767));
                        code[i + 1] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                        code[i + 2] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                        changed = true;
                        continue;
                    }
                }
            }
            
            // Pattern 3: MOVE R1, R2 → MOVE R2, R1 (redundant moves)
            if (op1 == OpCode::OP_MOVE && op2 == OpCode::OP_MOVE && A1 == B2 && A2 == B1) {
                code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                code[i + 1] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                changed = true;
                continue;
            }
            
            // Pattern 4: LOADINT R1, 0 → ADD R2, R3, R1 → MOVE R2, R3 (+0 identity)
            if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_ADD) {
                int val = static_cast<int>(Bx1) - 32767;
                if (val == 0 && C2 == A1) {
                    code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                    code[i + 1] = encodeABC(OpCode::OP_MOVE, A2, B2, 0);
                    changed = true;
                    continue;
                }
                if (val == 0 && B2 == A1) {
                    code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                    code[i + 1] = encodeABC(OpCode::OP_MOVE, A2, C2, 0);
                    changed = true;
                    continue;
                }
            }
            
            // Pattern 5: LOADINT R1, 1 → MUL R2, R3, R1 → MOVE R2, R3 (*1 identity)
            if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_MUL) {
                int val = static_cast<int>(Bx1) - 32767;
                if (val == 1 && C2 == A1) {
                    code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                    code[i + 1] = encodeABC(OpCode::OP_MOVE, A2, B2, 0);
                    changed = true;
                    continue;
                }
                if (val == 1 && B2 == A1) {
                    code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                    code[i + 1] = encodeABC(OpCode::OP_MOVE, A2, C2, 0);
                    changed = true;
                    continue;
                }
            }
            
            // Pattern 6: LOADINT R1, 0 → MUL R2, R3, R1 → LOADINT R2, 0 (*0 = 0)
            if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_MUL) {
                int val = static_cast<int>(Bx1) - 32767;
                if (val == 0 && (C2 == A1 || B2 == A1)) {
                    code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                    code[i + 1] = encodeABx(OpCode::OP_LOADINT, A2, 32767);  // LOAD 0
                    changed = true;
                    continue;
                }
            }
            
            // Pattern 7: MOVE R1, R2 → OP R3, R1, X → OP R3, R2, X (propagate through move)
            // This is handled by register allocation, but we can optimize redundant moves
            if (op1 == OpCode::OP_MOVE && A1 == B2) {
                // MOVE R1, R2 followed by instruction using R1 as source
                // Can potentially use R2 directly
                // This is a more complex optimization, skip for now
            }
            
            // Pattern 8: LOADBOOL R1, 1 → LOADBOOL R2, 0 → AND R3, R1, R2 → LOADBOOL R3, 0
            if (op1 == OpCode::OP_LOADBOOL && op2 == OpCode::OP_LOADBOOL) {
                if (i + 2 < code.size()) {
                    uint32_t instr3 = code[i + 2];
                    OpCode op3 = DECODE_OP(instr3);
                    uint8_t A3 = DECODE_A(instr3);
                    uint8_t B3 = DECODE_B(instr3);
                    uint8_t C3 = DECODE_C(instr3);
                    
                    if (op3 == OpCode::OP_AND && B3 == A1 && C3 == A2) {
                        // AND with false is always false
                        code[i] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                        code[i + 1] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);  // NOP
                        code[i + 2] = encodeABC(OpCode::OP_LOADBOOL, A3, 0, 0);
                        changed = true;
                        continue;
                    }
                }
            }
        }
        
        // Remove NOP instructions (compact the code)
        if (changed) {
            size_t writeIdx = 0;
            for (size_t readIdx = 0; readIdx < code.size(); readIdx++) {
                if (DECODE_OP(code[readIdx]) != OpCode::OP_LOADNULL || 
                    DECODE_A(code[readIdx]) != 0) {
                    code[writeIdx++] = code[readIdx];
                }
            }
            code.resize(writeIdx);
        }
    }
}
