#include "Compiler.h"
#include <ranges>
#include <stdexcept>
#include <algorithm>
#include <unordered_set>

using namespace iris::bytecode;
using namespace iris::core;
using namespace iris::node;

Chunk Compiler::compile(ProgramNode* program) {
    compileProgram(program);
    chunk.emit(encodeABC(OpCode::OP_HALT, 0, 0, 0));
    
    // OPTIMIZATION: Run peephole optimizer on generated bytecode
    peepholeOptimize(chunk);
    
    return std::move(chunk);
}

void Compiler::compileNode(ASTNode* node) {
    switch (node->getStmtType()) {
        case StmtType::Program: compileProgram(static_cast<ProgramNode*>(node)); return;
        case StmtType::Repeat: compileRepeat(static_cast<RepeatNode*>(node)); return;
        case StmtType::While: compileWhile(static_cast<WhileNode*>(node)); return;
        case StmtType::For: compileFor(static_cast<ForNode*>(node)); return;
        case StmtType::If: compileIf(static_cast<IfNode*>(node)); return;
        case StmtType::Print: compileLog(static_cast<PrintNode*>(node)); return;
        case StmtType::VarDecl: compileVarDecl(static_cast<VarDeclNode*>(node)); return;
        case StmtType::Assignment: compileAssignment(static_cast<AssignmentNode*>(node)); return;
        case StmtType::Wait: compileWait(static_cast<WaitNode*>(node)); return;
        case StmtType::Break: compileBreak(); return;
        case StmtType::Continue: compileContinue(); return;
        case StmtType::FunctionDecl: compileFunctionDecl(static_cast<FunctionDeclNode*>(node)); return;
        case StmtType::Return: compileReturn(static_cast<ReturnNode*>(node)); return;
        case StmtType::ClassDecl: compileClassDecl(static_cast<ClassDeclNode*>(node)); return;
        case StmtType::FieldAssign: compileFieldAssign(static_cast<FieldAssignNode*>(node)); return;
        case StmtType::ExprStmt: compileExprStmt(static_cast<ExpressionStmtNode*>(node)); return;
        case StmtType::IndexAssign: compileIndexAssign(static_cast<IndexAssignNode*>(node)); return;
        case StmtType::TryCatch: compileTryCatch(static_cast<TryCatchNode*>(node)); return;
        case StmtType::Throw: compileThrow(static_cast<ThrowNode*>(node)); return;
        case StmtType::Switch: compileSwitch(static_cast<SwitchNode*>(node)); return;
        case StmtType::Enum: compileEnum(static_cast<EnumNode*>(node)); return;
        case StmtType::ImportNative: compileImportNative(static_cast<ImportNativeNode*>(node)); return;
        default:
            throw std::runtime_error("Compiler: unknown AST node type");
    }
}

void Compiler::compileImportNative(ImportNativeNode* node) {
    throw std::runtime_error("Unknown native entity: " + node->name);
}

ExprResult Compiler::compileExpression(ExpressionNode* expr, uint8_t dst) {
    if (dst == 255) dst = allocReg();
    switch (expr->getExprType()) {
        case ExprType::Number: return compileNumber(static_cast<NumberNode*>(expr), dst);
        case ExprType::Double: return compileDouble(static_cast<DoubleNode*>(expr), dst);
        case ExprType::Boolean: return compileBoolean(static_cast<BooleanNode*>(expr), dst);
        case ExprType::String: return compileString(static_cast<StringNode*>(expr), dst);
        case ExprType::Variable: return compileVariable(static_cast<VariableNode*>(expr), dst);
        case ExprType::BinaryOp: return compileBinaryOp(static_cast<BinaryOperationNode*>(expr), dst);
        case ExprType::UnaryOp: return compileUnaryOp(static_cast<UnaryOperationNode*>(expr), dst);
        case ExprType::FunctionCall: return compileFunctionCall(static_cast<FunctionCallNode*>(expr), dst);
        case ExprType::FieldAccess: return compileFieldAccess(static_cast<FieldAccessNode*>(expr), dst);
        case ExprType::MethodCall: return compileMethodCall(static_cast<MethodCallNode*>(expr), dst);
        case ExprType::IndexAccess: return compileIndexAccess(static_cast<IndexAccessNode*>(expr), dst);
        case ExprType::ArrayAlloc: return compileArrayAlloc(static_cast<ArrayAllocNode*>(expr), dst);
        case ExprType::ArrayLiteral: return compileArrayLiteral(static_cast<ArrayLiteralNode*>(expr), dst);
        case ExprType::StringInterp: return compileStringInterp(static_cast<StringInterpNode*>(expr), dst);
        default:
            throw std::runtime_error("Compiler: unknown expression node type");
    }
}

void Compiler::compileProgram(ProgramNode* node) {
    for (auto& stmt : node->statements) {
        compileNode(stmt.get());
    }
}

void Compiler::compileLog(PrintNode* node) {
    uint8_t save = nextReg;
    ExprResult res = compileExpression(node->msg.get());
    chunk.emit(encodeABC(OpCode::OP_LOG, res.reg, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileWait(WaitNode* node) {
    uint8_t save = nextReg;
    ExprResult res = compileExpression(node->duration.get());
    chunk.emit(encodeABC(OpCode::OP_WAIT, res.reg, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileVarDecl(VarDeclNode* node) {
    const TypeAnnotation annot = node->typeAnnotation;
    if (isGlobalScope()) {
        uint16_t slot;
        auto it = globalIndex.find(node->nameOfVariable);
        if (it == globalIndex.end()) {
            slot = globalCount++;
            globalIndex[node->nameOfVariable] = slot;
        } else {
            slot = it->second;
        }
        uint8_t save = nextReg;
        ExprResult res = compileExpression(node->expression.get());
        // Runtime type check if annotation is present
        if (annot != TypeAnnotation::None)
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, res.reg, static_cast<uint8_t>(annot), 0));
        chunk.emit(encodeABC(OpCode::OP_DGLOB, res.reg, static_cast<uint8_t>(slot >> 8), static_cast<uint8_t>(slot & 0xFF)));
        freeRegsTo(save);
    } else {
        addLocal(node->nameOfVariable, node->isMutable, annot);
        int idx = resolveLocal(node->nameOfVariable);
        ExprResult res = compileExpression(node->expression.get(), locals[idx].reg);
        // If compiler knows the type, update it
        if (locals[idx].typeAnnot == TypeAnnotation::None) locals[idx].typeAnnot = res.type;
        
        // Runtime type check if annotation is present
        if (annot != TypeAnnotation::None)
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(annot), 0));
    }

    // Track class type for field/method access
    if (node->expression->getExprType() == ExprType::FunctionCall) {
        auto* call = static_cast<FunctionCallNode*>(node->expression.get());
        if (classIndex.contains(call->name)) {
            varClassMap[node->nameOfVariable] = call->name;
        }
    }
}

void Compiler::compileAssignment(AssignmentNode* node) {
    int arg = resolveLocal(node->nameOfVariable);
    if (arg != -1) {
        if (!locals[arg].isMutable) throw std::runtime_error("Variable is immutable.");
        compileExpression(node->expression.get(), locals[arg].reg);
    } else {
        auto it = globalIndex.find(node->nameOfVariable);
        if (it == globalIndex.end()) throw std::runtime_error("Undefined variable.");
        uint8_t save = nextReg;
        ExprResult res = compileExpression(node->expression.get());
        chunk.emit(encodeABx(OpCode::OP_SGLOB, res.reg, it->second));
        freeRegsTo(save);
    }
}

void Compiler::compileIf(IfNode* node) {
    uint8_t save = nextReg;
    ExprResult cond = compileExpression(node->condition.get());

    size_t thenJump = chunk.emitJump(OpCode::OP_JMPF, cond.reg);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->thenBlock) compileNode(stmt.get());
    endScope();

    size_t elseJump = chunk.emitJump(OpCode::OP_JMP);
    chunk.patchJump(thenJump);

    beginScope();
    for (auto& stmt : node->elseBlock) compileNode(stmt.get());
    endScope();

    chunk.patchJump(elseJump);
}

void Compiler::compileWhile(WhileNode* node) {
    const size_t loopStart = chunk.code.size();
    loopStack.push_back({loopStart, {}, scopeDepth});

    uint8_t save = nextReg;
    ExprResult cond = compileExpression(node->condition.get());

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, cond.reg);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
}

void Compiler::compileFor(const ForNode* node) {
    beginScope();
    if (node->init) compileNode(node->init.get());

    const size_t loopStart = chunk.code.size();
    uint8_t save = nextReg;
    ExprResult cond = compileExpression(node->condition.get());

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, cond.reg);
    freeRegsTo(save);

    loopStack.push_back({0, {}, scopeDepth});

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    loopStack.back().loopStart = chunk.code.size();
    if (node->increment) compileNode(node->increment.get());

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
    endScope();
}

void Compiler::compileRepeat(RepeatNode* node) {
    beginScope();
    const std::string counterName = "$__repeat_" + std::to_string(repeatCounter++);
    addLocal(counterName, true, TypeAnnotation::Int);

    int counterIdx = resolveLocal(counterName);
    uint8_t counterReg = locals[counterIdx].reg;

    compileExpression(node->count.get(), counterReg);

    const size_t loopStart = chunk.code.size();
    loopStack.push_back({loopStart, {}, scopeDepth});

    uint8_t save = nextReg;
    uint8_t zeroReg = allocReg();
    chunk.emit(encodeABx(OpCode::OP_LOADINT, zeroReg, static_cast<uint16_t>(0 + 32767)));
    uint8_t condReg = allocReg();
    chunk.emit(encodeABC(OpCode::OP_GT_INT, condReg, counterReg, zeroReg));

    size_t exitJump = chunk.emitJump(OpCode::OP_JMPF, condReg);
    freeRegsTo(save);

    beginScope();
    for (auto& stmt : node->body) compileNode(stmt.get());
    endScope();

    save = nextReg;
    uint8_t oneReg = allocReg();
    chunk.emit(encodeABx(OpCode::OP_LOADINT, oneReg, 1 + 32767));
    chunk.emit(encodeABC(OpCode::OP_SUB_INT, counterReg, counterReg, oneReg));
    freeRegsTo(save);

    chunk.emitLoop(loopStart);
    chunk.patchJump(exitJump);

    for (size_t breakJump : loopStack.back().breakJumps) {
        chunk.patchJump(breakJump);
    }
    loopStack.pop_back();
    endScope();
}

void Compiler::compileBreak() {
    if (loopStack.empty()) throw std::runtime_error("'break' outside loop");
    loopStack.back().breakJumps.push_back(chunk.emitJump(OpCode::OP_JMP));
}

void Compiler::compileContinue() {
    if (loopStack.empty()) throw std::runtime_error("'continue' outside loop");
    chunk.emitLoop(loopStack.back().loopStart);
}

void Compiler::compileFunctionDecl(FunctionDeclNode* node) {
    uint16_t funcIdx = static_cast<uint16_t>(functions.size());
    functionIndex[node->name] = funcIdx;
    functions.push_back({});

    // Save compiler state
    Chunk savedChunk = std::move(chunk);
    std::vector<Local> savedLocals = std::move(locals);
    int savedScopeDepth = scopeDepth;
    auto savedLoopStack = std::move(loopStack);
    uint8_t savedNextReg = nextReg;
    uint8_t savedMaxReg = maxReg;

    // Reset for new function
    chunk = Chunk{};
    locals.clear();
    scopeDepth = 0;
    loopStack.clear();
    nextReg = 0;
    maxReg = 0;

    beginScope();
    // Add params as locals, emit OP_TYPECHECK for typed params
    for (auto& [pname, ptype] : node->params) {
        addLocal(pname, true, ptype);
        if (ptype != TypeAnnotation::None) {
            int idx = resolveLocal(pname);
            chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(ptype), 0));
        }
    }
    for (auto& stmt : node->body) compileNode(stmt.get());

    // Implicit return null
    uint8_t nullReg = allocReg();
    chunk.emit(encodeABC(OpCode::OP_LOADNULL, nullReg, 0, 0));
    chunk.emit(encodeABC(OpCode::OP_RET, nullReg, 0, 0));

    functions[funcIdx].name = node->name;
    functions[funcIdx].arity = static_cast<int>(node->params.size());
    functions[funcIdx].chunk = std::move(chunk);
    functions[funcIdx].maxRegs = maxReg;
    functions[funcIdx].returnType = node->returnType;
    // Store param types for call-site checking
    functions[funcIdx].paramTypes.reserve(node->params.size());
    for (auto& [pname, ptype] : node->params)
        functions[funcIdx].paramTypes.push_back(ptype);

    // Restore state
    chunk = std::move(savedChunk);
    locals = std::move(savedLocals);
    scopeDepth = savedScopeDepth;
    loopStack = std::move(savedLoopStack);
    nextReg = savedNextReg;
    maxReg = savedMaxReg;
}

void Compiler::compileReturn(ReturnNode* node) {
    if (node->expression) {
        if (node->expression->getExprType() == ExprType::FunctionCall) {
            auto* call = static_cast<FunctionCallNode*>(node->expression.get());
            if (call->name != "print" && call->name != "wait" && 
                call->name != "array" && call->name != "len" && call->name != "super") {
                auto it = functionIndex.find(call->name);
                if (it != functionIndex.end()) {
                    uint8_t save = nextReg;
                    uint8_t base = nextReg;
                    for (auto& arg : call->args) {
                        allocReg();
                        compileExpression(arg.get(), nextReg - 1);
                    }
                    chunk.emit(encodeABC(OpCode::OP_TAILCALL, base, 
                                        static_cast<uint8_t>(it->second & 0xFF), 
                                        static_cast<uint8_t>(call->args.size())));
                    freeRegsTo(save);
                    return;
                }
            }
        } 
        else if (node->expression->getExprType() == ExprType::MethodCall) {
            auto* call = static_cast<MethodCallNode*>(node->expression.get());
            if (call->objectName != "super") {
                uint8_t save = nextReg;
                uint8_t base = nextReg;
                const uint8_t objReg = allocReg();

                if (call->objectName == "this") {
                    int thisLocal = resolveLocal("this");
                    if (thisLocal == -1) 
                        throw std::runtime_error("this.method() must be called from a method");
                    if (locals[thisLocal].reg != objReg) 
                        chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
                } else {
                    int localIdx = resolveLocal(call->objectName);
                    if (localIdx != -1) {
                        if (locals[localIdx].reg != objReg) 
                            chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[localIdx].reg, 0));
                    } else {
                        auto gIt = globalIndex.find(call->objectName);
                        if (gIt == globalIndex.end()) 
                            throw std::runtime_error("Undefined variable '" + call->objectName + "'");
                        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
                    }
                }

                for (auto& arg : call->args) {
                    allocReg();
                    compileExpression(arg.get(), nextReg - 1);
                }

                uint8_t totalArgs = static_cast<uint8_t>(call->args.size() + 1);
                uint16_t nameId = chunk.addConstant(Value(call->methodName));
                if (nameId > 255) 
                    throw std::runtime_error("Too many unique strings in chunk for OP_TAIL_INVOKE B byte");
                chunk.emit(encodeABC(OpCode::OP_TAIL_INVOKE, base, 
                                    static_cast<uint8_t>(nameId), totalArgs));
                freeRegsTo(save);
                return;
            }
        }
    }

    const uint8_t save = nextReg;
    uint8_t r;
    if (node->expression) {
        r = compileExpression(node->expression.get()).reg;
    } else {
        r = allocReg();
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, r, 0, 0));
    }
    chunk.emit(encodeABC(OpCode::OP_RET, r, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileClassDecl(ClassDeclNode* node) {
    uint16_t clsId = static_cast<uint16_t>(classes.size());
    classIndex[node->name] = clsId;
    ClassMeta meta;
    meta.name = node->name;

    if (!node->parentName.empty()) {
        auto parentIt = classIndex.find(node->parentName);
        if (parentIt == classIndex.end())
            throw std::runtime_error("Unknown parent class: " + node->parentName);
        
        uint16_t parentId = parentIt->second;
        meta.parentClassId = static_cast<int16_t>(parentId);
        auto& parentMeta = classes[parentId];

        for (uint16_t i = 0; i < parentMeta.fields.size(); i++) {
            meta.fields.push_back(parentMeta.fields[i]);
            meta.fieldIndex[parentMeta.fields[i].name] = i;
        }

        for (auto& [methodName, funcIdx] : parentMeta.methodIndex) {
            meta.methodIndex[methodName] = funcIdx;
            meta.methodPublic[methodName] = parentMeta.methodPublic[methodName];
        }
        
        for (const auto& absM : parentMeta.abstractMethods) {
            meta.abstractMethods.push_back(absM);
        }
    }

    meta.isAbstract = node->isAbstract;

    for (uint16_t i = 0; i < node->fields.size(); i++) {
        auto& f = node->fields[i];
        uint16_t fieldIdx = static_cast<uint16_t>(meta.fields.size());
        meta.fields.push_back({f.name, f.isMutable, f.isPublic});
        meta.fieldIndex[f.name] = fieldIdx;
    }

    std::string savedClassName = currentClassName;
    currentClassName = node->name;

    for (auto& m : node->methods) {
        auto* funcDecl = m.function.get();
        const std::string& methName = funcDecl->name;

        if (m.isAbstract) {
            if (!meta.isAbstract) {
                throw std::runtime_error("Class '" + meta.name + "' is not abstract and cannot contain abstract method '" + methName + "'");
            }
            if (std::find(meta.abstractMethods.begin(), meta.abstractMethods.end(), methName) == meta.abstractMethods.end()) {
                meta.abstractMethods.push_back(methName);
            }
            meta.methodIndex[methName] = 0xFFFF;
            meta.methodPublic[methName] = m.isPublic;
            continue;
        }

        auto it = std::find(meta.abstractMethods.begin(), meta.abstractMethods.end(), methName);
        if (it != meta.abstractMethods.end()) {
            meta.abstractMethods.erase(it);
        }

        std::vector<std::pair<std::string, TypeAnnotation>> params;
        params.emplace_back("this", TypeAnnotation::None);
        for (auto& p : funcDecl->params) {
            params.push_back(p);
        }

        uint16_t funcIdx = static_cast<uint16_t>(functions.size());
        std::string qualName = node->name + "." + methName;
        functionIndex[qualName] = funcIdx;
        meta.methodIndex[methName] = funcIdx;
        meta.methodPublic[methName] = m.isPublic;
        functions.push_back({});

        Chunk savedChunk = std::move(chunk);
        std::vector<Local> savedLocals = std::move(locals);
        int savedScopeDepth = scopeDepth;
        auto savedLoopStack = std::move(loopStack);
        uint8_t savedNextReg = nextReg;
        uint8_t savedMaxReg = maxReg;

        chunk = Chunk{};
        locals.clear();
        scopeDepth = 0;
        loopStack.clear();
        nextReg = 0;
        maxReg = 0;

        beginScope();
        for (auto& [pname, ptype] : params) {
            addLocal(pname, true, ptype);
            if (ptype != TypeAnnotation::None) {
                int idx = resolveLocal(pname);
                chunk.emit(encodeABC(OpCode::OP_TYPECHECK, locals[idx].reg, static_cast<uint8_t>(ptype), 0));
            }
        }
        for (auto& stmt : funcDecl->body) compileNode(stmt.get());

        uint8_t nullReg = allocReg();
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, nullReg, 0, 0));
        chunk.emit(encodeABC(OpCode::OP_RET, nullReg, 0, 0));

        functions[funcIdx].name = qualName;
        functions[funcIdx].arity = static_cast<int>(params.size());
        functions[funcIdx].chunk = std::move(chunk);
        functions[funcIdx].maxRegs = maxReg;
        functions[funcIdx].returnType = funcDecl->returnType;
        functions[funcIdx].paramTypes.reserve(params.size());
        for (auto& [pn, pt] : params)
            functions[funcIdx].paramTypes.push_back(pt);

        chunk = std::move(savedChunk);
        locals = std::move(savedLocals);
        scopeDepth = savedScopeDepth;
        loopStack = std::move(savedLoopStack);
        nextReg = savedNextReg;
        maxReg = savedMaxReg;
    }

    if (!meta.isAbstract && !meta.abstractMethods.empty()) {
        throw std::runtime_error("Class '" + meta.name + "' is not abstract and does not implement abstract method '" + meta.abstractMethods[0] + "' from parent");
    }

    classes.push_back(std::move(meta));
    currentClassName = savedClassName;
}

void Compiler::compileFieldAssign(FieldAssignNode* node) {
    std::string className;
    if (node->objectName == "this") {
        className = currentClassName;
    } else {
        auto it = varClassMap.find(node->objectName);
        if (it == varClassMap.end()) throw std::runtime_error("Unknown class for '" + node->objectName + "'");
        className = it->second;
    }

    auto& meta = classes[classIndex[className]];
    auto fieldIt = meta.fieldIndex.find(node->fieldName);
    if (fieldIt == meta.fieldIndex.end())
        throw std::runtime_error("Unknown field '" + node->fieldName + "' on class '" + className + "'");

    if (!meta.fields[fieldIt->second].isPublic && currentClassName != className)
        throw std::runtime_error("Cannot access private field '" + node->fieldName + "'");
    if (!meta.fields[fieldIt->second].isMutable && node->objectName != "this")
        throw std::runtime_error("Cannot assign to immutable field '" + node->fieldName + "'");

    uint8_t save = nextReg;
    uint8_t objReg;
    int localIdx = resolveLocal(node->objectName);
    if (localIdx != -1) {
        objReg = locals[localIdx].reg;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        objReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
    }

    ExprResult val = compileExpression(node->expression.get());
    chunk.emit(encodeABC(OpCode::OP_SET_FIELD, val.reg, objReg, static_cast<uint8_t>(fieldIt->second)));
    freeRegsTo(save);
}

void Compiler::compileExprStmt(ExpressionStmtNode* node) {
    uint8_t save = nextReg;
    compileExpression(node->expression.get());
    freeRegsTo(save);
}

ExprResult Compiler::compileFieldAccess(FieldAccessNode* node, uint8_t dst) {
    std::string className;
    if (node->objectName == "this") {
        className = currentClassName;
    } else {
        auto it = varClassMap.find(node->objectName);
        if (it == varClassMap.end()) {
            // Check if it might be an enum (stored as Global "EnumName.Value")
            std::string fullName = node->objectName + "." + node->fieldName;
            auto gIt = globalIndex.find(fullName);
            if (gIt != globalIndex.end()) {
                chunk.emit(encodeABx(OpCode::OP_GGLOB, dst, gIt->second));
                return {dst, TypeAnnotation::Int}; // Enums are Int
            }
            throw std::runtime_error("Unknown class or enum for '" + node->objectName + "'");
        }
        className = it->second;
    }

    auto& meta = classes[classIndex[className]];
    auto fieldIt = meta.fieldIndex.find(node->fieldName);
    if (fieldIt == meta.fieldIndex.end())
        throw std::runtime_error("Unknown field '" + node->fieldName + "' on class '" + className + "'");

    if (!meta.fields[fieldIt->second].isPublic && currentClassName != className)
        throw std::runtime_error("Cannot access private field '" + node->fieldName + "'");

    uint8_t save = nextReg;
    uint8_t objReg;
    int localIdx = resolveLocal(node->objectName);
    if (localIdx != -1) {
        objReg = locals[localIdx].reg;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        objReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
    }

    chunk.emit(encodeABC(OpCode::OP_GET_FIELD, dst, objReg, static_cast<uint8_t>(fieldIt->second)));
    freeRegsTo(save + 1);
    return {dst, TypeAnnotation::None};
}

ExprResult Compiler::compileMethodCall(MethodCallNode* node, uint8_t dst) {
    if (node->objectName == "super") {
        if (currentClassName.empty()) throw std::runtime_error("super.method() can only be used inside a class");
        auto clsIt = classIndex.find(currentClassName);
        if (clsIt == classIndex.end()) throw std::runtime_error("Internal error");
        auto& meta = classes[clsIt->second];
        if (meta.parentClassId < 0) throw std::runtime_error("super used in class '" + currentClassName + "' which has no parent");
        
        auto& pMeta = classes[meta.parentClassId];
        auto pIt = pMeta.methodIndex.find(node->methodName);
        if (pIt == pMeta.methodIndex.end()) throw std::runtime_error("Unknown method '" + node->methodName + "' on parent class");
        
        uint16_t funcIdx = pIt->second;
        uint8_t base = nextReg;
        uint8_t objReg = allocReg();
        
        int thisLocal = resolveLocal("this");
        if (thisLocal == -1) throw std::runtime_error("super.method() must be called from a method with 'this'");
        if (locals[thisLocal].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
        
        for (auto& arg : node->args) {
            allocReg();
            compileExpression(arg.get(), nextReg - 1);
        }
        
        uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
        chunk.emit(encodeABC(OpCode::OP_CALL, base, static_cast<uint8_t>(funcIdx & 0xFF), totalArgs));
        freeRegsTo(base + 1);
        if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
        return {dst, TypeAnnotation::None};
    }

    uint8_t base = nextReg;
    const uint8_t objReg = allocReg();

    if (node->objectName == "this") {
        int thisLocal = resolveLocal("this");
        if (thisLocal == -1) throw std::runtime_error("this.method() must be called from a method");
        if (locals[thisLocal].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[thisLocal].reg, 0));
    } else {
        int localIdx = resolveLocal(node->objectName);
        if (localIdx != -1) {
            if (locals[localIdx].reg != objReg) chunk.emit(encodeABC(OpCode::OP_MOVE, objReg, locals[localIdx].reg, 0));
        } else {
            auto gIt = globalIndex.find(node->objectName);
            if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
            chunk.emit(encodeABx(OpCode::OP_GGLOB, objReg, gIt->second));
        }
    }

    for (auto& arg : node->args) {
        allocReg();
        compileExpression(arg.get(), nextReg - 1);
    }

    uint8_t totalArgs = static_cast<uint8_t>(node->args.size() + 1);
    uint16_t nameId = chunk.addConstant(Value(node->methodName));
    chunk.emit(encodeABC(OpCode::OP_INVOKE, base, static_cast<uint8_t>(nameId), totalArgs));

    freeRegsTo(base + 1);
    if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
    return {dst, TypeAnnotation::None};
}

ExprResult Compiler::compileFunctionCall(FunctionCallNode* node, uint8_t dst) {
    if (node->name == "print") {
        if (node->args.size() != 1) throw std::runtime_error("print() expects 1 arg");
        uint8_t save = nextReg;
        ExprResult res = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_LOG, res.reg, 0, 0));
        freeRegsTo(save);
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, dst, 0, 0));
        return {dst, TypeAnnotation::None};
    }
    if (node->name == "wait") {
        if (node->args.size() != 1) throw std::runtime_error("wait() expects 1 arg");
        uint8_t save = nextReg;
        ExprResult res = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_WAIT, res.reg, 0, 0));
        freeRegsTo(save);
        chunk.emit(encodeABC(OpCode::OP_LOADNULL, dst, 0, 0));
        return {dst, TypeAnnotation::None};
    }

    if (node->name == "array") {
        if (node->args.size() != 1) throw std::runtime_error("array() expects 1 arg (size)");
        uint8_t save = nextReg;
        ExprResult sizeRes = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeRes.reg, 0));
        freeRegsTo(save + 1);
        return {dst, TypeAnnotation::None};
    }
    if (node->name == "len") {
        if (node->args.size() != 1) throw std::runtime_error("len() expects 1 arg");
        uint8_t save = nextReg;
        ExprResult collRes = compileExpression(node->args[0].get());
        chunk.emit(encodeABC(OpCode::OP_COLL_LEN, dst, collRes.reg, 0));
        freeRegsTo(save + 1);
        return {dst, TypeAnnotation::Int};
    }

    auto it = functionIndex.find(node->name);
    if (it != functionIndex.end()) {
        uint8_t base = nextReg;
        for (auto& arg : node->args) {
            allocReg();
            compileExpression(arg.get(), nextReg - 1);
        }
        chunk.emit(encodeABC(OpCode::OP_CALL, base, static_cast<uint8_t>(it->second & 0xFF), static_cast<uint8_t>(node->args.size())));
        freeRegsTo(base + 1);
        if (dst != base) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, base, 0));
        return {dst, functions[it->second].returnType};
    }
    
    // Class instantiation
    auto classIt = classIndex.find(node->name);
    if (classIt != classIndex.end()) {
        uint16_t clsId = classIt->second;
        chunk.emit(encodeABx(OpCode::OP_NEW_OBJ, dst, clsId));
        return {dst, TypeAnnotation::None};
    }

    throw std::runtime_error("Undefined function: " + node->name);
}

ExprResult Compiler::compileNumber(NumberNode* node, uint8_t dst) {
    int val = node->value;
    if (val >= -32767 && val <= 32767) {
        chunk.emit(encodeABx(OpCode::OP_LOADINT, dst, static_cast<uint16_t>(val + 32767)));
    } else {
        uint16_t ki = chunk.addConstant(Value(val));
        chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    }
    return {dst, TypeAnnotation::Int};
}

ExprResult Compiler::compileDouble(DoubleNode* node, uint8_t dst) {
    uint16_t ki = chunk.addConstant(Value(node->value));
    chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    return {dst, TypeAnnotation::Double};
}

ExprResult Compiler::compileBoolean(BooleanNode* node, uint8_t dst) {
    chunk.emit(encodeABC(OpCode::OP_LOADBOOL, dst, node->value ? 1 : 0, 0));
    return {dst, TypeAnnotation::Bool};
}

ExprResult Compiler::compileString(StringNode* node, uint8_t dst) {
    uint16_t ki = chunk.addConstant(Value(node->value));
    chunk.emit(encodeABx(OpCode::OP_LOADK, dst, ki));
    return {dst, TypeAnnotation::String};
}

ExprResult Compiler::compileVariable(VariableNode* node, uint8_t dst) {
    int arg = resolveLocal(node->nameOfVariable);
    if (arg != -1) {
        uint8_t srcReg = locals[arg].reg;
        if (srcReg != dst) chunk.emit(encodeABC(OpCode::OP_MOVE, dst, srcReg, 0));
        return {dst, locals[arg].typeAnnot};
    }
    auto it = globalIndex.find(node->nameOfVariable);
    if (it == globalIndex.end()) throw std::runtime_error("Undefined variable.");
    chunk.emit(encodeABx(OpCode::OP_GGLOB, dst, it->second));
    return {dst, TypeAnnotation::None};
}

ExprResult Compiler::compileUnaryOp(UnaryOperationNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    ExprResult res = compileExpression(node->operand.get());
    if (node->operation == "!") {
        chunk.emit(encodeABC(OpCode::OP_NOT, dst, res.reg, 0));
        freeRegsTo(save + 1);
        return {dst, TypeAnnotation::Bool};
    } else if (node->operation == "-") {
        chunk.emit(encodeABC(OpCode::OP_NEG, dst, res.reg, 0));
        freeRegsTo(save + 1);
        return {dst, res.type};
    }
    throw std::runtime_error("Unknown unary operator");
}

ExprResult Compiler::compileBinaryOp(BinaryOperationNode* node, uint8_t dst) {
    static const std::unordered_map<std::string, OpCode> opTable = {
        {"+", OpCode::OP_ADD}, {"-", OpCode::OP_SUB}, {"*", OpCode::OP_MUL},
        {"/", OpCode::OP_DIV}, {"%", OpCode::OP_MOD},
        {"==", OpCode::OP_EQ}, {"!=", OpCode::OP_NEQ},
        {"<", OpCode::OP_LT}, {">", OpCode::OP_GT},
        {"<=", OpCode::OP_LE}, {">=", OpCode::OP_GE},
        {"&&", OpCode::OP_AND}, {"||", OpCode::OP_OR},
        {"&", OpCode::OP_BIT_AND}, {"|", OpCode::OP_BIT_OR}, {"^", OpCode::OP_BIT_XOR},
        {"<<", OpCode::OP_SHL}, {">>", OpCode::OP_SHR},
    };

    uint8_t save = nextReg;
    ExprResult left = compileExpression(node->leftNode.get());
    ExprResult right = compileExpression(node->rightNode.get());

    const auto& op = node->operation;
    OpCode specialized = OpCode::OP_COUNT;
    TypeAnnotation resultType = TypeAnnotation::None;

    if (left.type == TypeAnnotation::Int && right.type == TypeAnnotation::Int) {
        resultType = TypeAnnotation::Int;
        if (op == "+") specialized = OpCode::OP_ADD_INT;
        else if (op == "-") specialized = OpCode::OP_SUB_INT;
        else if (op == "*") specialized = OpCode::OP_MUL_INT;
        else if (op == "/") specialized = OpCode::OP_DIV_INT;
        else if (op == "<") { specialized = OpCode::OP_LT_INT; resultType = TypeAnnotation::Bool; }
        else if (op == ">") { specialized = OpCode::OP_GT_INT; resultType = TypeAnnotation::Bool; }
        else if (op == "<=") { specialized = OpCode::OP_LE_INT; resultType = TypeAnnotation::Bool; }
        else if (op == ">=") { specialized = OpCode::OP_GE_INT; resultType = TypeAnnotation::Bool; }
        else if (op == "==") { specialized = OpCode::OP_EQ_INT; resultType = TypeAnnotation::Bool; }
    } else if ((left.type == TypeAnnotation::Double || left.type == TypeAnnotation::Int) && 
               (right.type == TypeAnnotation::Double || right.type == TypeAnnotation::Int)) {
        resultType = TypeAnnotation::Double;
        if (op == "+") specialized = OpCode::OP_ADD_DOUBLE;
        else if (op == "-") specialized = OpCode::OP_SUB_DOUBLE;
        else if (op == "*") specialized = OpCode::OP_MUL_DOUBLE;
        else if (op == "/") specialized = OpCode::OP_DIV_DOUBLE;
        else if (op == "<") { specialized = OpCode::OP_LT_DBL; resultType = TypeAnnotation::Bool; }
        else if (op == ">") { specialized = OpCode::OP_GT_DBL; resultType = TypeAnnotation::Bool; }
        else if (op == "<=") { specialized = OpCode::OP_LE_DBL; resultType = TypeAnnotation::Bool; }
        else if (op == ">=") { specialized = OpCode::OP_GE_DBL; resultType = TypeAnnotation::Bool; }
        else if (op == "==") { specialized = OpCode::OP_EQ_DBL; resultType = TypeAnnotation::Bool; }
    }

    if (specialized != OpCode::OP_COUNT) {
        chunk.emit(encodeABC(specialized, dst, left.reg, right.reg));
    } else {
        auto it = opTable.find(node->operation);
        if (it == opTable.end()) throw std::runtime_error("Unknown binary operator");
        chunk.emit(encodeABC(it->second, dst, left.reg, right.reg));
    }
    
    freeRegsTo(save + 1);
    return {dst, resultType};
}

void Compiler::beginScope() {
    scopeDepth++;
}

void Compiler::endScope() {
    scopeDepth--;
    while (!locals.empty() && locals.back().depth > scopeDepth) {
        locals.pop_back();
        freeReg();
    }
}

void Compiler::addLocal(const std::string& name, bool isMutable, TypeAnnotation typeAnnot) {
    for (auto & local : std::ranges::reverse_view(locals)) {
        if (local.depth < scopeDepth) break;
        if (local.name == name) throw std::runtime_error("Variable redeclared: " + name);
    }
    uint8_t r = allocReg();
    locals.push_back({name, scopeDepth, isMutable, r, typeAnnot});
}

int Compiler::resolveLocal(const std::string& name) {
    for (int i = static_cast<int>(locals.size()) - 1; i >= 0; i--) {
        if (locals[i].name == name) return i;
    }
    return -1;
}

ExprResult Compiler::compileIndexAccess(IndexAccessNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    ExprResult coll = compileExpression(node->object.get());
    ExprResult idx = compileExpression(node->index.get());

    OpCode op = OpCode::OP_IDX_GET;
    TypeAnnotation elemType = TypeAnnotation::None;

    if (coll.type == TypeAnnotation::DoubleArray) { op = OpCode::OP_IDX_GET_DBL; elemType = TypeAnnotation::Double; }
    else if (coll.type == TypeAnnotation::IntArray) { op = OpCode::OP_IDX_GET_INT; elemType = TypeAnnotation::Int; }

    chunk.emit(encodeABC(op, dst, coll.reg, idx.reg));
    freeRegsTo(save + 1);
    return {dst, elemType};
}

void Compiler::compileIndexAssign(IndexAssignNode* node) {
    uint8_t save = nextReg;
    OpCode op = OpCode::OP_IDX_SET;

    int localIdx = resolveLocal(node->objectName);
    uint8_t collReg;
    if (localIdx != -1) {
        collReg = locals[localIdx].reg;
        if (locals[localIdx].typeAnnot == TypeAnnotation::DoubleArray) op = OpCode::OP_IDX_SET_DBL;
        else if (locals[localIdx].typeAnnot == TypeAnnotation::IntArray) op = OpCode::OP_IDX_SET_INT;
    } else {
        auto gIt = globalIndex.find(node->objectName);
        if (gIt == globalIndex.end()) throw std::runtime_error("Undefined variable '" + node->objectName + "'");
        collReg = allocReg();
        chunk.emit(encodeABx(OpCode::OP_GGLOB, collReg, gIt->second));
    }

    ExprResult idx = compileExpression(node->index.get());
    ExprResult val = compileExpression(node->value.get());
    chunk.emit(encodeABC(op, val.reg, collReg, idx.reg));
    freeRegsTo(save);
}

ExprResult Compiler::compileArrayAlloc(ArrayAllocNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    ExprResult sizeRes = compileExpression(node->size.get());

    uint8_t elemTypeTag = 0;
    if (node->elementType == TypeAnnotation::Int || node->elementType == TypeAnnotation::IntArray) elemTypeTag = 1;
    else if (node->elementType == TypeAnnotation::Double || node->elementType == TypeAnnotation::DoubleArray) elemTypeTag = 2;
    else if (node->elementType == TypeAnnotation::String || node->elementType == TypeAnnotation::StringArray) elemTypeTag = 3;
    else if (node->elementType == TypeAnnotation::Bool || node->elementType == TypeAnnotation::BoolArray) elemTypeTag = 3;

    chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeRes.reg, elemTypeTag));
    freeRegsTo(save + 1);
    
    TypeAnnotation resType = TypeAnnotation::None;
    if (elemTypeTag == 1) resType = TypeAnnotation::IntArray;
    else if (elemTypeTag == 2) resType = TypeAnnotation::DoubleArray;
    else if (elemTypeTag == 3) resType = TypeAnnotation::StringArray; // simplified

    return {dst, resType};
}

ExprResult Compiler::compileArrayLiteral(ArrayLiteralNode* node, uint8_t dst) {
    uint8_t save = nextReg;
    int size = static_cast<int>(node->elements.size());

    uint8_t sizeReg = allocReg();
    if (size >= -32767 && size <= 32767) {
        chunk.emit(encodeABx(OpCode::OP_LOADINT, sizeReg, static_cast<uint16_t>(size + 32767)));
    } else {
        uint16_t ki = chunk.addConstant(Value(size));
        chunk.emit(encodeABx(OpCode::OP_LOADK, sizeReg, ki));
    }

    chunk.emit(encodeABC(OpCode::OP_NEW_ARRAY, dst, sizeReg, 0));

    for (int i = 0; i < size; ++i) {
        uint8_t valSave = nextReg;
        ExprResult valRes = compileExpression(node->elements[i].get());

        uint8_t idxReg = allocReg();
        if (i >= -32767 && i <= 32767) {
            chunk.emit(encodeABx(OpCode::OP_LOADINT, idxReg, static_cast<uint16_t>(i + 32767)));
        } else {
            uint16_t ki = chunk.addConstant(Value(i));
            chunk.emit(encodeABx(OpCode::OP_LOADK, idxReg, ki));
        }

        chunk.emit(encodeABC(OpCode::OP_IDX_SET, valRes.reg, dst, idxReg));
        freeRegsTo(valSave);
    }

    freeRegsTo(save + 1);
    return {dst, TypeAnnotation::None};
}

void Compiler::compileTryCatch(TryCatchNode* node) {
    uint8_t catchVarReg = allocReg();
    
    uint32_t pushInstrIndex = static_cast<uint32_t>(chunk.code.size());
    chunk.emit(encodeABx(OpCode::OP_PUSH_HANDLER, catchVarReg, 0));

    for (auto& stmt : node->tryBody) {
        compileNode(stmt.get());
    }

    chunk.emit(encodeABC(OpCode::OP_POP_HANDLER, 0, 0, 0));
    uint32_t jmpOverCatch = static_cast<uint32_t>(chunk.code.size());
    chunk.emit(encodesBx(OpCode::OP_JMP, 0));

    uint32_t catchStart = static_cast<uint32_t>(chunk.code.size());
    int16_t catchOffset = static_cast<int16_t>(catchStart - (pushInstrIndex + 1));
    chunk.code[pushInstrIndex] = encodeABx(OpCode::OP_PUSH_HANDLER, catchVarReg, static_cast<uint16_t>(catchOffset));

    beginScope();
    addLocal(node->catchVar, true, TypeAnnotation::String);
    locals.back().reg = catchVarReg;
    
    for (auto& stmt : node->catchBody) {
        compileNode(stmt.get());
    }
    endScope();

    nextReg = catchVarReg;

    uint32_t endCatch = static_cast<uint32_t>(chunk.code.size());
    int16_t offsetToEnd = static_cast<int16_t>(endCatch - (jmpOverCatch + 1));
    chunk.code[jmpOverCatch] = encodesBx(OpCode::OP_JMP, offsetToEnd);
}

ExprResult Compiler::compileStringInterp(StringInterpNode* node, uint8_t dst) {
    if (node->parts.empty()) {
        chunk.emit(encodeABx(OpCode::OP_LOADK, dst, static_cast<uint16_t>(chunk.addConstant(Value("")))));
        return {dst, TypeAnnotation::String};
    }

    uint8_t save = nextReg;
    ExprResult res = compileExpression(node->parts[0].get());
    if (res.reg != dst) {
        chunk.emit(encodeABC(OpCode::OP_MOVE, dst, res.reg, 0));
    }

    for (size_t i = 1; i < node->parts.size(); i++) {
        ExprResult r = compileExpression(node->parts[i].get());
        chunk.emit(encodeABC(OpCode::OP_ADD, dst, dst, r.reg));
    }

    freeRegsTo(save + 1);
    return {dst, TypeAnnotation::String};
}

void Compiler::compileThrow(ThrowNode* node) {
    uint8_t save = nextReg;
    ExprResult res = compileExpression(node->expression.get());
    chunk.emit(encodeABC(OpCode::OP_THROW, res.reg, 0, 0));
    freeRegsTo(save);
}

void Compiler::compileSwitch(SwitchNode* node) {
    uint8_t save = nextReg;
    ExprResult exprRes = compileExpression(node->expression.get());
    
    std::vector<size_t> endJumps;
    size_t defaultIdx = size_t(-1);

    for (size_t i = 0; i < node->cases.size(); i++) {
        auto& c = node->cases[i];
        if (!c->value) {
            defaultIdx = i;
            continue;
        }

        uint8_t caseSave = nextReg;
        ExprResult valRes = compileExpression(c->value.get());
        uint8_t condReg = allocReg();
        chunk.emit(encodeABC(OpCode::OP_EQ, condReg, exprRes.reg, valRes.reg));
        
        size_t nextCaseJump = chunk.emitJump(OpCode::OP_JMPF, condReg);
        freeRegsTo(caseSave);

        beginScope();
        for (auto& stmt : c->body) compileNode(stmt.get());
        endScope();

        endJumps.push_back(chunk.emitJump(OpCode::OP_JMP));
        chunk.patchJump(nextCaseJump);
    }

    if (defaultIdx != size_t(-1)) {
        beginScope();
        for (auto& stmt : node->cases[defaultIdx]->body) compileNode(stmt.get());
        endScope();
    }

    for (size_t jump : endJumps) {
        chunk.patchJump(jump);
    }

    freeRegsTo(save);
}

void Compiler::compileEnum(EnumNode* node) {
    for (auto& [valName, valInt] : node->values) {
        std::string fullName = node->name + "." + valName;
        uint16_t slot;
        auto it = globalIndex.find(fullName);
        if (it == globalIndex.end()) {
            slot = globalCount++;
            globalIndex[fullName] = slot;
        } else {
            slot = it->second;
        }

        uint8_t r = allocReg();
        if (valInt >= -32767 && valInt <= 32767) {
            chunk.emit(encodeABx(OpCode::OP_LOADINT, r, static_cast<uint16_t>(valInt + 32767)));
        } else {
            uint16_t ki = chunk.addConstant(Value(valInt));
            chunk.emit(encodeABx(OpCode::OP_LOADK, r, ki));
        }
        chunk.emit(encodeABC(OpCode::OP_DGLOB, r, static_cast<uint8_t>(slot >> 8), static_cast<uint8_t>(slot & 0xFF)));
        freeReg();
    }
}

void Compiler::peepholeOptimize(Chunk& ch) {
    auto& code = ch.code;
    if (code.empty()) return;
    
    std::unordered_set<size_t> jumpTargets;
    for (size_t i = 0; i < code.size(); i++) {
        OpCode op = decodeOp(code[i]);
        if (op == OpCode::OP_JMP || op == OpCode::OP_JMPF || op == OpCode::OP_LOOP) {
            int16_t offset = static_cast<int16_t>(decodeSBx(code[i]));
            jumpTargets.insert(i + 1 + offset);
        }
    }
    
    bool changed = true;
    int iterations = 0;
    const int MAX_ITERATIONS = 10;
    
    while (changed && iterations < MAX_ITERATIONS) {
        changed = false;
        iterations++;
        
        for (size_t i = 0; i + 1 < code.size(); i++) {
            if (jumpTargets.contains(i + 1)) continue;
            
            uint32_t instr1 = code[i];
            uint32_t instr2 = code[i + 1];
            
            OpCode op1 = decodeOp(instr1);
            OpCode op2 = decodeOp(instr2);
            
            uint8_t A1 = decodeA(instr1);
            uint16_t Bx1 = decodeBx(instr1);
            uint8_t A2 = decodeA(instr2);
            uint8_t B2 = decodeB(instr2);
            
            if (op1 == OpCode::OP_LOADINT && op2 == OpCode::OP_MOVE && A1 == B2) {
                code[i + 1] = encodeABx(OpCode::OP_LOADINT, A2, Bx1);
                changed = true;
                continue;
            }
            
            uint8_t B1 = decodeB(instr1);
            if (op1 == OpCode::OP_MOVE && op2 == OpCode::OP_MOVE && A1 == B2 && A2 == B1) {
                code[i + 1] = encodeABC(OpCode::OP_LOADNULL, 0, 0, 0);
                changed = true;
                continue;
            }
        }
    }
}
